### ISSUE TITLE
Benchmarking with zig

### ISSUE THREAD

**Issue by voroskoi** [AliChraghi/zort#4]
Hi,

Using hyperfine for benchmarking is OK, but in my opinion it would be much better to use a zig implementation. I am not saying that I will even write the graph part, but the bechmarking and outputting to json seems manageable.

Are You interested in such contributions? I would only start it if You are open for this.

Thanks,

**Comment by alichraghi** [comment]
yea that makes sense. feel free to do that. Thanks :)
