### ISSUE TITLE
wrong tim sort implementation

### ISSUE THREAD

**Issue by voroskoi** [AliChraghi/zort#8]
Hi Ali,

I have just read this article: http://www.envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/

Is Your implementation affected or You were aware of this issue?

**Comment by sharpobject** [comment]
It seems like the timsort in this repository is incorrect close to 100% of the time, which is probably due to a different bug.

**Comment by alichraghi** [comment]
yes current tim sort is completely wrong and have to be rewritten like main Java implementation

**Comment by voroskoi** [comment]
I would like to give it a go. Assigned to myself, if somebody already working on this speak up!
